#JWT
jwt.secret=fl0atieG4me2025Secr3tK3yForJWT!ChangeThisInProduction
jwt.expiration=86400000

# CORS ? local dev only
app.cors.allowed-origins=http://localhost:4200

# DB
# Database connection (required)
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=floatie
spring.datasource.password=floatie123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# Pet mechanics: 1 real minute = 1 game hour (60x speed)
app.pet.time-multiplier=6000.0

# Logging
logging.level.com.future.floatie=DEBUG
logging.level.org.springframework.security=INFO