server.port=8080
spring.application.name=floatie-backend
app.uploads.directory=${UPLOADS_DIR:./backend/sprites}
app.pixel-art.sprite-size=128
app.pixel-art.pixel-scale=4
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# Logging
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%5p) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n