server.port=8080
spring.application.name=floatie-backend

# DB
# Database connection (required)
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=floatie
spring.datasource.password=floatie123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=fl0atieG4me2025Secr3tK3yForJWT!ChangeThisInProduction
jwt.expiration=86400000

# Logging
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%5p) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n